apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: student-feedback
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dockermajid/student-feedback-frontend:40592bf983adeb51b6fa85ac1aaff31fad79009e
          imagePullPolicy: Always
          ports:
            - containerPort: 80
