apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: student-feedback
type: opaque
stringData:
  POSTGRES_DB: feedbackdb
  POSTGRES_USER: feedbackuser
  POSTGRES_PASSWORD: feedbackuser