apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-feedback
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/majid-gt/student-feedback-k8s.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: student-feedback
  syncPolicy:
    automated:
      prune: true
      selfHeal: true